name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ github.repository }}:${{ github.sha }}

      - name: SSH into server and build Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/study/
            docker build -t sky-edu-mobile:${{ github.sha }} .
            
      - name: SSH into server and deploy Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker stop sky-edu-mobile || true
            docker rm sky-edu-mobile || true
            docker run -d \
                       --name sky-edu-mobile \
                       -p 5174:80 \
                       sky-edu-mobile:${{ github.sha }}
